version: '2'

services:
    db:
        image: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_HOST_PORT}:3306
    redis:
        build:
            context: redis
            args:
                TIMEZONE: ${TIMEZONE}
        ports:
            - 16379:6379
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
    nginx:
        build: nginx
        ports:
            - ${NGINX_HOST_PORT}:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    socketio:
        build:
            context: socketio
            args:
                TIMEZONE: ${TIMEZONE}
        ports:
            - 10081:8080
        volumes_from:
            - php
        volumes:
            - ./socketapp/:/srv/socketapp/
#    elk:
#        image: willdurand/elk
#        ports:
#            - 81:80
#        volumes:
#            - ./elk/logstash:/etc/logstash
#            - ./elk/logstash/patterns:/opt/logstash/patterns
#        volumes_from:
#            - php
#            - nginx
